services:
  mfins:
    build:
      context: ./mfins
      dockerfile: Dockerfile
    image: metakgp/mfins
    container_name: mfins
    volumes:
      - $MFINS_CONFIG/.env:/app/.env
      - $MFINS_CONFIG/client_secret.json:/app/client_secret.json
      - $MFINS_CONFIG/erpcreds.json:/app/erpcreds.json
      - $MFINS_CONFIG/lastmsg.json:/app/lastmsg.json
      - $MFINS_CONFIG/.token:/app/.token
      - $MFINS_CONFIG/.session:/app/.session